name = "embun-laundry"
main = "src/index.js"
compatibility_date = "2024-09-01"

[assets]
directory = "./public"

[vars]
TIDB_DATABASE = "embun_laundry"
JWT_SECRET = "dhani-laundry-secure-jwt-secret-key-2026"
TIDB_DATABASE_URL = "mysql://nkLgGwz1mobWK3U.root:ugNFt1lVM749mRHd@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/embun_laundry?ssl={\"rejectUnauthorized\":true}"